### ISSUE TITLE
Q: react native compatible

### ISSUE THREAD

**Issue by glycerine** [myitcv/react#105]
Just out of curiosity, as I'm big Go fan but new to react and learning about react and react native: Is this library meant to be compatible with the native version too?  Thanks!

**Comment by myitcv** [comment]
Hi @glycerine - in theory it should be possible to also support React Native, although I've not tried it. 

Would require use to separate out the DOM bit (which is currently mixed up with the React core wrapper itself) but we could do that via a separate package or a build tag.

**Comment by glycerine** [comment]
Cool. Thanks Paul.
