### ISSUE TITLE
react.go line 71 conflicts with naming on HTML5 element `<s>`

### ISSUE THREAD

**Issue by grkuntzmd** [myitcv/react#121]
When generating the `<s>` element [(strikethrough)](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/s), the generated function `S` to create a new `<s>` conflicts with the type alias `type S = core.S` on line 71 in `react.go`.

**Comment by myitcv** [comment]
Hmm this is unfortunate. Will give it some thought.

**Comment by myitcv** [comment]
Noting that [`<strike>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strike) is deprecated, I think my preference here would be to use `Strike` and document that it corresponds to `<s>`. The shorthand `react.S` for a string value will be used far _far_ more often than the `<s>` element.
