### ISSUE TITLE
jsx.HTML silently fails to render valid input

### ISSUE THREAD

**Issue by jcramb** [myitcv/react#146]
Firstly, thanks very much for your work on these react bindings - they've been great so far!

I encountered an issue while trying to use the simpler and much more expressive jsx.HTML, introduced by #64, instead of needing to construct all elements using chained functions. To my knowledge the following examples are logically equivalent, yet one renders correctly using jsx.HTML while the other fails to emit the html elements.

**Example which succeeds:**
```
func (c NavbarDef) Render() react.Element {
	return react.Div(nil, jsx.HTML(`
		<nav><ul><li>
			Testing
		</li></ul></nav>
	`)...)
}
```

**Example which fails:**
```
func (c NavbarDef) Render() react.Element {
	return react.Div(nil, jsx.HTML(`
		<nav><ul><li>Testing</li>
		</ul></nav>
	`)...)
}
```

My initial thought is potentially an issue with incorrect newline handling?

**Comment by myitcv** [comment]
@jcramb 

> Firstly, thanks very much for your work on these react bindings - they've been great so far!

Good to hear, but please keep the feedback coming! As things stand I intend to also try and port them to use the WASM backend when that stabilises.

Thanks for the report of the issue; I think I've recreated that using @dave's brilliant https://github.com/dave/jsgo:

https://play.jsgo.io/bb98775cc9864c1250f278bd9d8eebaefe864457

If you look in the developer console, the issue appears to be that the `Ul` element is being passed a `react.S` (string) value... when it (the `Ul` element) only knows how to accept `react.RendersLi` values.

Just noting that analysis for now; will come back to this when I have more time.

**Comment by myitcv** [comment]
@jcramb - please checkout the latest commit in `master` (d3a8968) which has a fix for this.

Thanks again for the report.
