### ISSUE TITLE
go get not working

### ISSUE THREAD

**Issue by pjebs** [myitcv/react#165]
`go get -u myitcv.io/react` returns

```
package myitcv.io/react: unrecognized import path "myitcv.io/react" (parse https://myitcv.io/react?go-get=1: multiple meta tags match import path "myitcv.io/react")
```

**Comment by pjebs** [comment]
I then tried:
`go get -u github.com/myitcv/react`

```
package github.com/myitcv/react: code in directory /Users/X/GOPATH/src/github.com/myitcv/react expects import "myitcv.io/react"
```

**Comment by myitcv** [comment]
Please can you confirm what version of Go you are using?

**Comment by pjebs** [comment]
`go version go1.10.1 darwin/amd64`

**Comment by myitcv** [comment]
Currently away from keyboard, so apologies for the terse response.

But please use 1.10.3 or later

You are seeing this message because all of my code has been moved to a Go
modules aware mono repo at https://github.com/myitcv/x

**Comment by myitcv** [comment]
Also @pjebs do you mind creating new issues over at https://github.com/myitcv/x? I'm in the process of archiving this repo, will add documentation redirects and will copy over existing issues when I do so.  Thanks
