### ISSUE TITLE
Lazy load

### ISSUE THREAD

**Issue by joeblew99** [myitcv/react#92]
i am amazed at how far you have taken this. Really impressive and useful. Hats off and looking forward to kicking the tires.

Some newbie stuff.
- the install client side is big. Is there are support of the PRPL pattern / Lazy load yet ?

- Themes. Yes i know its lame, but well was wondering... Material Design maybe ?

**Comment by myitcv** [comment]
> i am amazed at how far you have taken this. Really impressive and useful.

Thanks @joeblew99 

> the install client side is big

Things definitely aren't fully optimised as yet. Looking at the most minimal example, http://blog.myitcv.io/gopherjs_examples_sites/helloworld/. Total size is `774K`. Of that, `152K` is minfied React code. Using Preact is smaller still at `49K`. I've got something in the [TODO list](https://github.com/myitcv/react/wiki/TODO) tracking optimising this further. Nothing as advanced as PRPL / lazy load (yet).

> Themes. Yes i know its lame, but well was wondering... Material Design maybe ?

You're totally free to do whatever you like as far as styling etc is concerned. `reactGen -init (minimal|bootstrap)` is really only to get you started... no constraints. 

Equally, if you'd like to contribute a different template, let me know. The `-init` mode of `reactGen` is very very hacky for now... so could do with a bit of tidy up before contributions in that space.

**Comment by joeblew99** [comment]
Thanks for the info.

For now i am busy on CRDT stuff using yjs. https://github.com/y-js/yjs.
Yjs allows you to do google docs style functionality very easily with
offline editting. I a, experimenting with it & boltDB as the buckets
concept maps to yjs really well.
Currently its standard JS, but looking to port to golang. It will allow
event store architectures to get automatic offline / online sync.
Would be nice addition to your framework..

As far as the other stuff, right now i just have to watch as too busy on
CRDT and other bits.
But just wanted to raise some things i saw for now.

cheers

Joe

**Comment by myitcv** [comment]
Sounds interesting @joeblew99!

Anything you want to track by keeping this issue open, given that I'll issues from my TODO?

Thanks

**Comment by joeblew99** [comment]
I got a PRPL server working with polymer yesterday. thanks to: https://github.com/CaptainCodeman/prpl-server-example

For me, its useful because you get cross builds (different browsers have different specs) and lazy loading.  
For gopherjs its also useful because with lazy loading you can get around the fact that gopherjs is a bit of a fatty :) I have not looked into how much work it woudl be to support it with gopherjs or even its its worth it.

Also as an aside, I run this on mobiles and servers at the moment. In mobiles you can run it as a service and server many apps with a webview.

**Comment by joeblew99** [comment]
lets close this
I will have a look at your todo list, and do some more tire kicking..

**Comment by myitcv** [comment]
👍

**Comment by myitcv** [comment]
Also @joeblew99 just in case you've not seen, the [Links](https://github.com/myitcv/react/wiki#links) of the wiki which has examples, creating your first app guide, talks links etc. 

Might be of some help - feedback much appreciated too.

**Comment by joeblew99** [comment]
@myitcv thansk mate. Yeah i was getting a bit lost in terms of how to reuse existing React components out there.

For intance, the code below is from the GRPCWeb example. 
You usng bootstrap and then rendering direct creating your own DOm elements as you go.
I am trying to work out if i can use a well known existing lib like Material-UI.
For example their button...
https://github.com/callemall/material-ui/blob/v1-beta/src/Button/Button.js

// Render renders the GetBook component
func (g GetBookDef) Render() r.Element {
	st := g.State()
	content := []r.Element{
		r.P(nil, r.S("Search for book by ISBN (for example, 140008381).")),
		r.Form(&r.FormProps{ClassName: "form-inline"},
			r.Div(
				&r.DivProps{ClassName: "form-group"},
				r.Label(&r.LabelProps{ClassName: "sr-only", For: "isnbText"}, r.S("ISBN")),
				r.Input(&r.InputProps{
					Type:      "number",
					ClassName: "form-control",
					ID:        "isnbText",
					Value:     st.isbnInput,
					OnChange:  isbnInputChange{g},
				}),
				r.Button(&r.ButtonProps{
					Type:      "submit",
					ClassName: "btn btn-default",
					OnClick:   triggerGet{g},
				}, r.S("Get Book")),
			),
		),
	}

	if st.book != nil {
		content = append(content, renderBook(st.book))
	}

	if st.err != "" {
		content = append(content,
			r.Div(nil,
				r.Hr(nil),
				r.S("Error: "+st.err),
			),
		)
	}

	return r.Div(nil, content...)
}
